services:
  frontend:
    container_name: nextjs_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    container_name: fastapi_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    # --reload: Will reload the server  --reload-include {file type}: will reload if you change the file you specified 
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-include *"
    ports:
      - 8000:8000
    # Will reload docker container when changes are made in the code
    volumes:
      - .:/backend/app
    depends_on:
      - db
    env_file:
      - "./backend/.env"
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5440:5432

volumes:
  db-data: {}
