export type Player = {
  player_id: number;
  first_last: string;
  first_name: string;
  last_name: string;
  birth_date: Date;
  school: string;
  country: string;
  height: string;
  weight: string;
  jersey: string;
  position: string;
  is_active: boolean;
  from_year: number;
  to_year: number;
  team_id: number;
  draft_year: string;
  draft_round: string;
  draft_number: string;
  image_url: string;
};
